export const GET_CUSTOMER_PROFILE = 'GET_CUSTOMER_PROFILE';
export const GET_CUSTOMER_PROFILE_SUCCESS = 'GET_CUSTOMER_PROFILE_SUCCESS';
export const GET_CUSTOMER_PROFILE_FAILED = 'GET_CUSTOMER_PROFILE_FAILED';

export const UPDATE_CUSTOMER_PROFILE = 'UPDATE_CUSTOMER_PROFILE';
export const UPDATE_CUSTOMER_PROFILE_SUCCESS = 'UPDATE_CUSTOMER_PROFILE_SUCCESS';
export const UPDATE_CUSTOMER_PROFILE_FAILED = 'UPDATE_CUSTOMER_PROFILE_FAILED';

export const UPDATE_CUSTOMER_PASSWORD = 'UPDATE_CUSTOMER_PASSWORD';
export const UPDATE_CUSTOMER_PASSWORD_SUCCESS = 'UPDATE_CUSTOMER_PASSWORD_SUCCESS';
export const UPDATE_CUSTOMER_PASSWORD_FAILED = 'UPDATE_CUSTOMER_PASSWORD_FAILED';

export const UPDATE_CUSTOMER_AVATAR = 'UPDATE_CUSTOMER_AVATAR';
export const UPDATE_CUSTOMER_AVATAR_SUCCESS = 'UPDATE_CUSTOMER_AVATAR_SUCCESS';
export const UPDATE_CUSTOMER_AVATAR_FAILED = 'UPDATE_CUSTOMER_AVATAR_FAILED';

export const UPDATE_CUSTOMER_ADDRESS = 'UPDATE_CUSTOMER_ADDRESS';
export const UPDATE_CUSTOMER_ADDRESS_SUCCESS = 'UPDATE_CUSTOMER_ADDRESS_SUCCESS';
export const UPDATE_CUSTOMER_ADDRESS_FAILED = 'UPDATE_CUSTOMER_ADDRESS_FAILED';

export const ADD_CUSTOMER_ADDRESS = 'ADD_CUSTOMER_ADDRESS';
export const ADD_CUSTOMER_ADDRESS_SUCCESS = 'ADD_CUSTOMER_ADDRESS_SUCCESS';
export const ADD_CUSTOMER_ADDRESS_FAILED = 'ADD_CUSTOMER_ADDRESS_FAILED';
