version: '1.0'

# Define services
services:
  # Database Service (Mysql)
  db:
    build: 
      context: home-service-database
      dockerfile: Dockerfile
      args:
        MYSQL_ROOT_PASSWORD: 123456
    image: huutien120802/home-service-database
    container_name: home-service-database-container
    ports:
      - 3307:3306
    restart: always
    environment:
      MYSQL_DATABASE: service_db
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend  

  # App backend service
  app-server:
    # Configuration for building the docker image for the backend service
    build:
      context: home-service-server # Use an image built from the specified dockerfile in the `polling-app-server` directory.
      dockerfile: Dockerfile
    image: huutien120802/home-service-server
    container_name: home-service-server-container
    ports:
      - "8080:8080" # Forward the exposed port 8080 on the container to port 8080 on the host machine
    restart: always
    depends_on: 
      - db # This service depends on mysql. Start that first.
    environment: # Pass environment variables to the service
      SPRING_DATASOURCE_HOST: home-service-database-container
      SPRING_DATASOURCE_PORT: 3306
      SPRING_DATASOURCE_DB_NAME: service_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
      ORIGIN_URL: http://localhost 
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend
      - frontend

  # Frontend Service 
  app-client:
    build:
      context: home-service-client # Use an image built from the specified dockerfile in the `polling-app-client` directory.
      dockerfile: Dockerfile
      args:
        REACT_APP_API_BASE_URL: http://home-service-server-container:8080/api/v1
    image: huutien120802/home-service-client
    container_name: home-service-client-container
    ports:
      - "80:80" # Forward the exposed port 80 on the container to port 80 on the host machine
    restart: always
    depends_on:
      - app-server
    environment:
      REACT_APP_API_BASE_URL: http://home-service-server-container:8080/api/v1
    networks:
      - frontend  

# Volumes
volumes:
  db-data:

# Networks to be created to facilitate communication between containers
networks:
  backend:
  frontend:    