// Service actions
export const GET_ALL_SERVICES = 'GET_ALL_SERVICES';
export const GET_ALL_SERVICES_SUCCESS = 'GET_ALL_SERVICES_SUCCESS';
export const GET_ALL_SERVICES_FAILED = 'GET_ALL_SERVICES_FAILED';

export const UPDATE_SERVICE = 'UPDATE_SERVICE';
export const UPDATE_SERVICE_SUCCESS = 'UPDATE_SERVICE_SUCCESS';
export const UPDATE_SERVICE_FAILED = 'UPDATE_SERVICE_FAILED';

export const CREATE_SERVICE = 'CREATE_SERVICE';
export const CREATE_SERVICE_SUCCESS = 'CREATE_SERVICE_SUCCESS';
export const CREATE_SERVICE_FAILED = 'CREATE_SERVICE_FAILED';

export const DELETE_SERVICE = 'DELETE_SERVICE';
export const DELETE_SERVICE_SUCCESS = 'DELETE_SERVICE_SUCCESS';
export const DELETE_SERVICE_FAILED = 'DELETE_SERVICE_FAILED';

// Provider actions
export const UPDATE_PROVIDER_PROFILE = 'UPDATE_PROVIDER_PROFILE';
export const UPDATE_PROVIDER_PROFILE_SUCCESS = 'UPDATE_PROVIDER_PROFILE_SUCCESS';
export const UPDATE_PROVIDER_PROFILE_FAILED = 'UPDATE_PROVIDER_PROFILE_FAILED';

export const DELETE_PROVIDER = 'DELETE_PROVIDER';
export const DELETE_PROVIDER_SUCCESS = 'DELETE_PROVIDER_SUCCESS';
export const DELETE_PROVIDER_FAILED = 'DELETE_PROVIDER_FAILED';

export const GET_ALL_PROVIDERS = 'GET_ALL_PROVIDERS';
export const GET_ALL_PROVIDERS_SUCCESS = 'GET_ALL_PROVIDERS_SUCCESS';
export const GET_ALL_PROVIDERS_FAILED = 'GET_ALL_PROVIDERS_FAILED';

export const CREATE_PROVIDER = 'CREATE_PROVIDER';
export const CREATE_PROVIDER_SUCCESS = 'CREATE_PROVIDER_SUCCESS';
export const CREATE_PROVIDER_FAILED = 'CREATE_PROVIDER_FAILED';

// Statistics actions
export const GET_SALES_STATISTICS = 'GET_SALES_STATISTICS';
export const GET_SALES_STATISTICS_SUCCESS = 'GET_SALES_STATISTICS_SUCCESS';
export const GET_SALES_STATISTICS_FAILED = 'GET_SALES_STATISTICS_FAILED';

export const GET_QUANTITY_STATISTICS = 'GET_QUANTITY_STATISTICS';
export const GET_QUANTITY_STATISTICS_SUCCESS = 'GET_QUANTITY_STATISTICS_SUCCESS';
export const GET_QUANTITY_STATISTICS_FAILED = 'GET_QUANTITY_STATISTICS_FAILED';

// Customer actions
export const UPDATE_CUSTOMER_PROFILE = 'UPDATE_CUSTOMER_PROFILE';
export const UPDATE_CUSTOMER_PROFILE_SUCCESS = 'UPDATE_CUSTOMER_PROFILE_SUCCESS';
export const UPDATE_CUSTOMER_PROFILE_FAILED = 'UPDATE_CUSTOMER_PROFILE_FAILED';

export const DELETE_CUSTOMER = 'DELETE_CUSTOMER';
export const DELETE_CUSTOMER_SUCCESS = 'DELETE_CUSTOMER_SUCCESS';
export const DELETE_CUSTOMER_FAILED = 'DELETE_CUSTOMER_FAILED';

export const GET_ALL_CUSTOMERS = 'GET_ALL_CUSTOMERS';
export const GET_ALL_CUSTOMERS_SUCCESS = 'GET_ALL_CUSTOMERS_SUCCESS';
export const GET_ALL_CUSTOMERS_FAILED = 'GET_ALL_CUSTOMERS_FAILED';

export const CREATE_CUSTOMER = 'CREATE_CUSTOMER';
export const CREATE_CUSTOMER_SUCCESS = 'CREATE_CUSTOMER_SUCCESS';
export const CREATE_CUSTOMER_FAILED = 'CREATE_CUSTOMER_FAILED';

// Review actions
export const GET_ALL_REVIEWS = 'GET_ALL_REVIEWS';
export const GET_ALL_REVIEWS_SUCCESS = 'GET_ALL_REVIEWS_SUCCESS';
export const GET_ALL_REVIEWS_FAILED = 'GET_ALL_REVIEWS_FAILED';

export const GET_REVIEW = 'GET_REVIEW';
export const GET_REVIEW_SUCCESS = 'GET_REVIEW_SUCCESS';
export const GET_REVIEW_FAILED = 'GET_REVIEW_FAILED';

export const DELETE_REVIEW = 'DELETE_REVIEW';
export const DELETE_REVIEW_SUCCESS = 'DELETE_REVIEW_SUCCESS';
export const DELETE_REVIEW_FAILED = 'DELETE_REVIEW_FAILED';

// Count entity action
export const GET_ENTITY_COUNT = 'GET_ENTITY_COUNT';
export const GET_ENTITY_COUNT_SUCCESS = 'GET_ENTITY_COUNT_SUCCESS';
export const GET_ENTITY_COUNT_FAILED = 'GET_ENTITY_COUNT_FAILED';

// Booking actions
export const GET_ALL_BOOKINGS = 'GET_ALL_BOOKINGS';
export const GET_ALL_BOOKINGS_SUCCESS = 'GET_ALL_BOOKINGS_SUCCESS';
export const GET_ALL_BOOKINGS_FAILED = 'GET_ALL_BOOKINGS_FAILED';

export const GET_BOOKING = 'GET_BOOKING';
export const GET_BOOKING_SUCCESS = 'GET_BOOKING_SUCCESS';
export const GET_BOOKING_FAILED = 'GET_BOOKING_FAILED';

export const DELETE_BOOKING = 'DELETE_BOOKING';
export const DELETE_BOOKING_SUCCESS = 'DELETE_BOOKING_SUCCESS';
export const DELETE_BOOKING_FAILED = 'DELETE_BOOKING_FAILED';

// Address actions
export const DELETE_ADDRESS = 'DELETE_ADDRESS';
export const DELETE_ADDRESS_SUCCESS = 'DELETE_ADDRESS_SUCCESS';
export const DELETE_ADDRESS_FAILED = 'DELETE_ADDRESS_FAILED';

export const APPROVE_OR_UNAPPROVE_REGISTER_SERVICE = 'APPROVE_OR_UNAPPROVE_REGISTER_SERVICE';
export const APPROVE_OR_UNAPPROVE_REGISTER_SERVICE_SUCCESS = 'APPROVE_OR_UNAPPROVE_REGISTER_SERVICE_SUCCESS';
export const APPROVE_OR_UNAPPROVE_REGISTER_SERVICE_FAILED = 'APPROVE_OR_UNAPPROVE_REGISTER_SERVICE_FAILED';

// Action types for /admin/count
export const GET_COUNT = 'GET_COUNT';
export const GET_COUNT_SUCCESS = 'GET_COUNT_SUCCESS';
export const GET_COUNT_FAILED = 'GET_COUNT_FAILED';
