export const UPDATE_BOOKING_STATUS = 'UPDATE_BOOKING_STATUS';
export const UPDATE_BOOKING_STATUS_SUCCESS = 'UPDATE_BOOKING_STATUS_SUCCESS';
export const UPDATE_BOOKING_STATUS_FAILED = 'UPDATE_BOOKING_STATUS_FAILED';

export const PROVIDER_CANCEL_BOOKING = 'PROVIDER_CANCEL_BOOKING';
export const PROVIDER_CANCEL_BOOKING_SUCCESS = 'PROVIDER_CANCEL_BOOKING_SUCCESS';
export const PROVIDER_CANCEL_BOOKING_FAILED = 'PROVIDER_CANCEL_BOOKING_FAILED';

export const CUSTOMER_CANCEL_BOOKING = 'CUSTOMER_CANCEL_BOOKING';
export const CUSTOMER_CANCEL_BOOKING_SUCCESS = 'CUSTOMER_CANCEL_BOOKING_SUCCESS';
export const CUSTOMER_CANCEL_BOOKING_FAILED = 'CUSTOMER_CANCEL_BOOKING_FAILED';

export const GET_CUSTOMER_BOOKINGS = 'GET_CUSTOMER_BOOKINGS';
export const GET_CUSTOMER_BOOKINGS_SUCCESS = 'GET_CUSTOMER_BOOKINGS_SUCCESS';
export const GET_CUSTOMER_BOOKINGS_FAILED = 'GET_CUSTOMER_BOOKINGS_FAILED';

export const CREATE_BOOKING = 'CREATE_BOOKING';
export const CREATE_BOOKING_SUCCESS = 'CREATE_BOOKING_SUCCESS';
export const CREATE_BOOKING_FAILED = 'CREATE_BOOKING_FAILED';

export const CREATE_BOOKING_CALC = 'CREATE_BOOKING_CALC';
export const CREATE_BOOKING_CALC_SUCCESS = 'CREATE_BOOKING_CALC_SUCCESS';
export const CREATE_BOOKING_CALC_FAILED = 'CREATE_BOOKING_CALC_FAILED';

export const GET_CUSTOMER_BOOKINGS_BY_STATUS = 'GET_CUSTOMER_BOOKINGS_BY_STATUS';
export const GET_CUSTOMER_BOOKINGS_BY_STATUS_SUCCESS = 'GET_CUSTOMER_BOOKINGS_BY_STATUS_SUCCESS';
export const GET_CUSTOMER_BOOKINGS_BY_STATUS_FAILED = 'GET_CUSTOMER_BOOKINGS_BY_STATUS_FAILED';

export const GET_PROVIDER_BOOKINGS = 'GET_PROVIDER_BOOKINGS';
export const GET_PROVIDER_BOOKINGS_SUCCESS = 'GET_PROVIDER_BOOKINGS_SUCCESS';
export const GET_PROVIDER_BOOKINGS_FAILED = 'GET_PROVIDER_BOOKINGS_FAILED';

export const SET_SELECTED_WORKS = 'SET_SELECTED_WORKS';
export const SET_SELECTED_WORKS_SUCCESS = 'SET_SELECTED_WORKS_SUCCESS';
export const SET_SELECTED_WORKS_FAILED = 'SET_SELECTED_WORKS_FAILED';

export const GET_PROVIDER_BOOKING = 'GET_PROVIDER_BOOKING';
export const GET_PROVIDER_BOOKING_SUCCESS = 'GET_PROVIDER_BOOKING_SUCCESS';
export const GET_PROVIDER_BOOKING_FAILED = 'GET_PROVIDER_BOOKING_FAILED';

export const GET_CUSTOMER_BOOKING = 'GET_CUSTOMER_BOOKING';
export const GET_CUSTOMER_BOOKING_SUCCESS = 'GET_CUSTOMER_BOOKING_SUCCESS';
export const GET_CUSTOMER_BOOKING_FAILED = 'GET_CUSTOMER_BOOKING_FAILED';
