export const GET_CUSTOMER_SERVICE_REVIEW = 'GET_CUSTOMER_SERVICE_REVIEW';
export const GET_CUSTOMER_SERVICE_REVIEW_SUCCESS = 'GET_CUSTOMER_SERVICE_REVIEW_SUCCESS';
export const GET_CUSTOMER_SERVICE_REVIEW_FAILED = 'GET_CUSTOMER_SERVICE_REVIEW_FAILED';

export const CREATE_CUSTOMER_SERVICE_REVIEW = 'CREATE_CUSTOMER_SERVICE_REVIEW';
export const CREATE_CUSTOMER_SERVICE_REVIEW_SUCCESS = 'CREATE_CUSTOMER_SERVICE_REVIEW_SUCCESS';
export const CREATE_CUSTOMER_SERVICE_REVIEW_FAILED = 'CREATE_CUSTOMER_SERVICE_REVIEW_FAILED';

export const GET_ALL_SERVICE_REVIEWS = 'GET_ALL_SERVICE_REVIEWS';
export const GET_ALL_SERVICE_REVIEWS_SUCCESS = 'GET_ALL_SERVICE_REVIEWS_SUCCESS';
export const GET_ALL_SERVICE_REVIEWS_FAILED = 'GET_ALL_SERVICE_REVIEWS_FAILED';
