export const GET_PROVIDER_PROFILE = 'GET_PROVIDER_PROFILE';
export const GET_PROVIDER_PROFILE_SUCCESS = 'GET_PROVIDER_PROFILE_SUCCESS';
export const GET_PROVIDER_PROFILE_FAILED = 'GET_PROVIDER_PROFILE_FAILED';

export const UPDATE_PROVIDER_PROFILE = 'UPDATE_PROVIDER_PROFILE';
export const UPDATE_PROVIDER_PROFILE_SUCCESS = 'UPDATE_PROVIDER_PROFILE_SUCCESS';
export const UPDATE_PROVIDER_PROFILE_FAILED = 'UPDATE_PROVIDER_PROFILE_FAILED';

export const UPDATE_PROVIDER_PASSWORD = 'UPDATE_PROVIDER_PASSWORD';
export const UPDATE_PROVIDER_PASSWORD_SUCCESS = 'UPDATE_PROVIDER_PASSWORD_SUCCESS';
export const UPDATE_PROVIDER_PASSWORD_FAILED = 'UPDATE_PROVIDER_PASSWORD_FAILED';

export const UPDATE_PROVIDER_AVATAR = 'UPDATE_PROVIDER_AVATAR';
export const UPDATE_PROVIDER_AVATAR_SUCCESS = 'UPDATE_PROVIDER_AVATAR_SUCCESS';
export const UPDATE_PROVIDER_AVATAR_FAILED = 'UPDATE_PROVIDER_AVATAR_FAILED';

export const UPDATE_PROVIDER_ADDRESS = 'UPDATE_PROVIDER_ADDRESS';
export const UPDATE_PROVIDER_ADDRESS_SUCCESS = 'UPDATE_PROVIDER_ADDRESS_SUCCESS';
export const UPDATE_PROVIDER_ADDRESS_FAILED = 'UPDATE_PROVIDER_ADDRESS_FAILED';

export const ADD_PROVIDER_ADDRESS = 'ADD_PROVIDER_ADDRESS';
export const ADD_PROVIDER_ADDRESS_SUCCESS = 'ADD_PROVIDER_ADDRESS_SUCCESS';
export const ADD_PROVIDER_ADDRESS_FAILED = 'ADD_PROVIDER_ADDRESS_FAILED';
