export const GET_ALL_SERVICES = 'GET_ALL_SERVICES';
export const GET_ALL_SERVICES_SUCCESS = 'GET_ALL_SERVICES_SUCCESS';
export const GET_ALL_SERVICES_FAILED = 'GET_ALL_SERVICES_FAILED';

export const GET_SERVICE_DETAILS = 'GET_SERVICE_DETAILS';
export const GET_SERVICE_DETAILS_SUCCESS = 'GET_SERVICE_DETAILS_SUCCESS';
export const GET_SERVICE_DETAILS_FAILED = 'GET_SERVICE_DETAILS_FAILED';
