export const GET_ALL_PROVIDER_SERVICES = 'GET_ALL_PROVIDER_SERVICES';
export const GET_ALL_PROVIDER_SERVICES_SUCCESS = 'GET_ALL_PROVIDER_SERVICES_SUCCESS';
export const GET_ALL_PROVIDER_SERVICES_FAILED = 'GET_ALL_PROVIDER_SERVICES_FAILED';

export const UPDATE_PROVIDER_SERVICE = 'UPDATE_PROVIDER_SERVICE';
export const UPDATE_PROVIDER_SERVICE_SUCCESS = 'UPDATE_PROVIDER_SERVICE_SUCCESS';
export const UPDATE_PROVIDER_SERVICE_FAILED = 'UPDATE_PROVIDER_SERVICE_FAILED';

export const REGISTER_PROVIDER_SERVICE = 'REGISTER_PROVIDER_SERVICE';
export const REGISTER_PROVIDER_SERVICE_SUCCESS = 'REGISTER_PROVIDER_SERVICE_SUCCESS';
export const REGISTER_PROVIDER_SERVICE_FAILED = 'REGISTER_PROVIDER_SERVICE_FAILED';

export const ENABLE_OR_DISABLE_PROVIDER_SERVICE = 'ENABLE_OR_DISABLE_PROVIDER_SERVICE';
export const ENABLE_OR_DISABLE_PROVIDER_SERVICE_SUCCESS = 'ENABLE_OR_DISABLE_PROVIDER_SERVICE_SUCCESS';
export const ENABLE_OR_DISABLE_PROVIDER_SERVICE_FAILED = 'ENABLE_OR_DISABLE_PROVIDER_SERVICE_FAILED';

export const APPROVE_OR_UNAPPROVE_REGISTER_SERVICE = 'APPROVE_OR_UNAPPROVE_REGISTER_SERVICE';
export const APPROVE_OR_UNAPPROVE_REGISTER_SERVICE_SUCCESS = 'APPROVE_OR_UNAPPROVE_REGISTER_SERVICE_SUCCESS';
export const APPROVE_OR_UNAPPROVE_REGISTER_SERVICE_FAILED = 'APPROVE_OR_UNAPPROVE_REGISTER_SERVICE_FAILED';

export const GET_ALL_PUBLIC_SERVICES = 'GET_ALL_PUBLIC_SERVICES';
export const GET_ALL_PUBLIC_SERVICES_SUCCESS = 'GET_ALL_PUBLIC_SERVICES_SUCCESS';
export const GET_ALL_PUBLIC_SERVICES_FAILED = 'GET_ALL_PUBLIC_SERVICES_FAILED';

export const GET_SERVICE_BY_ID = 'GET_SERVICE_BY_ID';
export const GET_SERVICE_BY_ID_SUCCESS = 'GET_SERVICE_BY_ID_SUCCESS';
export const GET_SERVICE_BY_ID_FAILED = 'GET_SERVICE_BY_ID_FAILED';

export const GET_PROVIDER_SERVICES_BY_STATUS = 'GET_PROVIDER_SERVICES_BY_STATUS';
export const GET_PROVIDER_SERVICES_BY_STATUS_SUCCESS = 'GET_PROVIDER_SERVICES_BY_STATUS_SUCCESS';
export const GET_PROVIDER_SERVICES_BY_STATUS_FAILED = 'GET_PROVIDER_SERVICES_BY_STATUS_FAILED';

export const DELETE_PROVIDER_SERVICE = 'DELETE_PROVIDER_SERVICE';
export const DELETE_PROVIDER_SERVICE_SUCCESS = 'DELETE_PROVIDER_SERVICE_SUCCESS';
export const DELETE_PROVIDER_SERVICE_FAILED = 'DELETE_PROVIDER_SERVICE_FAILED';
