name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login Docker hub
      run: echo ${{ secrets.REGISTRY_PASS }} | docker login -u ${{ secrets.REGISTRY_USER }} --password-stdin
    - name: Build and Push the Docker image
      run: docker compose build | docker compose push
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Pull && Re-reun services
      uses: appleboy/ssh-action@master
      with:
        username: ${{secrets.USER_NAME}}
        host:  ${{secrets.SSH_HOST}}
        password: ${{secrets.PASSWORD}}
        script: "docker compose stop && docker compose up --pull=always -d"
