name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login Docker hub
      run: echo ${{ secrets.REGISTRY_PASS }} | docker login -u ${{ secrets.REGISTRY_USER }} --password-stdin
    - name: Build the Docker image
      run: docker build -t huutien120802/app-server .
    - name: Push Docker Image
      run: docker push huutien120802/app-server
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: SSH into server
      run: sshpass -p ${{ secrets.ROOT_PASS }} ssh -tt root@103.146.23.19
    - name: Pull image and re-run
      run: |
        docker compose stop
        docker compose pull
        docker compose up -d
  
