name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login Docker hub
      run: echo ${{ secrets.REGISTRY_PASS }} | docker login -u ${{ secrets.REGISTRY_USER }} --password-stdin
    - name: Build the Docker image
      run: docker build -t huutien120802/app-server .
    - name: Push Docker Image
      run: docker push huutien120802/app-server
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Pull && Re-reun services
      env:
        PRIVATE_KEY: ${{ secrets.SSH_KEY }}
        HOSTNAME: ${{secrets.SSH_HOST}}
        USER_NAME: ${{secrets.USER_NAME}}
        PASSWORD: ${{secrets.PASSWORD}}
      run: 
        sshpass -p $PASSWORD ssh -o StrictHostKeyChecking=no $USER_NAME@$HOSTNAME "docker compose stop && docker compose up --pull=always -d"
